# This file configures the analyzer
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_build_context_synchronously: false
    library_private_types_in_public_api: false
    curly_braces_in_flow_control_structures: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

analyzer:
  errors:
    # Silenciamos avisos específicos para dejar el análisis en 0
    use_build_context_synchronously: ignore
    library_private_types_in_public_api: ignore
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
