// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCPbd2VOinSwg2FkosSKQmzRBi1RkbyMw',
    appId: '1:847754643180:web:6d9ad455315a565bcdc7c9',
    messagingSenderId: '847754643180',
    projectId: 'asystemcobacam',
    authDomain: 'asystemcobacam.firebaseapp.com',
    storageBucket: 'asystemcobacam.firebasestorage.app',
    measurementId: 'G-2EQEP55GYM',
    databaseURL: 'https://asystemcobacam-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_TgZ-0x-NcNMpMJB86Yo_7yUnfoVWkok',
    appId: '1:847754643180:android:26e661c1f8438cf9cdc7c9',
    messagingSenderId: '847754643180',
    projectId: 'asystemcobacam',
    storageBucket: 'asystemcobacam.firebasestorage.app',
    databaseURL: 'https://asystemcobacam-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ9Kk5QcvnTGyOU3q3GXPr_sXsQ-dyyVg',
    appId: '1:847754643180:ios:3547f5e2af4281cbcdc7c9',
    messagingSenderId: '847754643180',
    projectId: 'asystemcobacam',
    storageBucket: 'asystemcobacam.firebasestorage.app',
    iosBundleId: 'com.example.asystemCobacam',
    databaseURL: 'https://asystemcobacam-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ9Kk5QcvnTGyOU3q3GXPr_sXsQ-dyyVg',
    appId: '1:847754643180:ios:3547f5e2af4281cbcdc7c9',
    messagingSenderId: '847754643180',
    projectId: 'asystemcobacam',
    storageBucket: 'asystemcobacam.firebasestorage.app',
    iosBundleId: 'com.example.asystemCobacam',
    databaseURL: 'https://asystemcobacam-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCPbd2VOinSwg2FkosSKQmzRBi1RkbyMw',
    appId: '1:847754643180:web:7fe9d09aab3505b1cdc7c9',
    messagingSenderId: '847754643180',
    projectId: 'asystemcobacam',
    authDomain: 'asystemcobacam.firebaseapp.com',
    storageBucket: 'asystemcobacam.firebasestorage.app',
    measurementId: 'G-WESWG871WM',
    databaseURL: 'https://asystemcobacam-default-rtdb.firebaseio.com/',
  );
}